# Environment variables
language: c
cache: ccache
os: linux
dist: bionic
git:
  depth: false
  quiet: true
  submodules: false
addons:
  apt:
    sources:
      - sourceline: ppa:ubuntu-toolchain-r/test
    packages:
      - &native_deps cmake yasm gcc-10 g++-10 ninja-build

env:
  global:
    - build_type=Release CC="ccache gcc-10" CXX="ccache g++-10" CCACHE_DIR=$HOME/.ccache CFLAGS=-Werror

# Default scripts
install:
  - "sudo chown -R travis: $CCACHE_DIR"
  - sort -u /proc/cpuinfo
  - cmake --version
  - $CC --version
  - for url in raw.githubusercontent.com/OpenVisualCloud/SVT-AV1-Resources/master randomderp.com; do curl -LO https://$url/video.tar.gz && break; done
  - tar xf video.tar.gz
script:
  - &base_script |
    mkdir -p "$TRAVIS_BUILD_DIR/Build/linux/${build_type:=Release}"
    cd "$TRAVIS_BUILD_DIR/Build/linux/$build_type"
    cmake "$TRAVIS_BUILD_DIR" -GNinja -DCMAKE_BUILD_TYPE="$build_type" -DCMAKE_INSTALL_PREFIX=/usr
    sudo -E ninja install
    cd "$TRAVIS_BUILD_DIR"
  - SvtAv1EncApp --preset 0 -i akiyo_cif.y4m -n 3
  - SvtAv1EncApp --preset 8 -i akiyo_cif.y4m -n 150
  - SvtAv1EncApp --preset 0 -i Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m -n 3
  - SvtAv1EncApp --preset 8 -i Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m -n 150
before_cache:
  - "sudo chown -R travis: $CCACHE_DIR"
  - ccache -c
  - ccache -s

# Build matrix
jobs:
  allow_failures:
    - arch: s390x
  fast_finish: true
  include:
    # Multiple CPU Architectures
    - name: Arm64 GCC build
      arch: arm64
    - name: PowerPC GCC build
      arch: ppc64le
    - name: IBM Z GCC build
      arch: s390x
    # Valgrind on Linux
    - name: Valgrind
      env: build_type=debug
      addons:
        apt:
          sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
          packages:
            - *native_deps
            - valgrind
      script:
        - *base_script
        - travis_wait 60 valgrind --error-exitcode=1 -- SvtAv1EncApp --preset 4 -i akiyo_cif.y4m -n 20 -b test1.ivf
