name: Cppcheck
on:
  push:
    paths-ignore:
      - "Docs/*"
      - .travis.yml
      - appveyor.yml
      - .gitignore
      - "*.md"
  pull_request:
    paths-ignore:
      - "Docs/*"
      - .travis.yml
      - appveyor.yml
      - .gitignore
      - "*.md"

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      # Default depth is 1
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y yasm cppcheck
      - name: Run CMake
        run: cmake -S . -B Build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run Cppcheck
        run: |
          cppcheck \
            --project=Build/compile_commands.json \
            --error-exitcode=1 \
            --enable=all \
            -j $(nproc) \
            --template="::error file={file},line={line},col={column}::{severity}: {message} ({id})\n{file}:{line}" \
            -ithird_party
