name: Style Check
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      # Default depth is 1
      - uses: actions/checkout@v2
      - name: Tab check
        if: always()
        run: |
          ! git grep -InP --heading "\t" -- . ':!third_party/**/*'
      - name: Carriage Return check
        if: always()
        run: |
          ! git grep -InP --heading "\r" -- . ':!third_party/**/*'
      - name: Trailing spaces
        if: always()
        run: |
          ! git grep -InP --heading " $" -- . ':!third_party/**/*' ':!*.patch'
      - name: Fetch upstream
        if: always()
        run: |
          git fetch -q https://github.com/OpenVisualCloud/SVT-AV1.git master
      - name: newline at EOF check
        if: always()
        run: |
          for file in $(
            git diff --name-only --diff-filter=d FETCH_HEAD -- . \
              ':!third_party' ':!test/e2e_test/test_vector_list.txt' \
              ':!test/vectors/smoking_test.cfg' ':!test/vectors/video_src.cfg' \
              ':!*.png'
          ); do
            if [ -n "$(tail -c1 "$file")" ]; then
              echo "No newline at end of $file"
              false
            fi
          done
      - name: Check commit message
        if: always()
        run: |
          for i in $(git rev-list HEAD ^FETCH_HEAD); do
            echo "Checking commit message of $i"
            msg="$(git log --format=%B -n 1 "$i")"
            if [ -n "$(sed -n 2p <<< "$msg")" ]; then
              echo "Malformed commit message in $i, second line must be empty"
              false
            fi
            if grep -q '\.$' <(head -1 <<< "$msg"); then
              echo "Malformed commit message in $i, trailing period in subject line"
              false
            fi
          done
